### PR TITLE
Add simple DH interface using published components

### PR DESCRIPTION
**Pull request by pkalita-lbl**
These changes add a barebones DataHarmonizer interface in a new `web` directory. It is built using the NPM-published components, so relying on a git submodule is no longer required. And since it isn't directly tied to the main DataHarmonizer repository you're free to customize this interface or modify it however you see fit. 

To run the interface:

```shell
cd web
yarn  # required once for initial installation of dependencies
yarn dev
```

### CODE REVIEW

**Comment by turbomam** [comment]
Any chance you could hang out on Zoom while I try it now?

**Comment by turbomam** [comment]
> 

can you remind me what we ahd to do to get yarn installed and working on my computer>

**Comment by turbomam** [comment]
Assumes that JSON version of schema has been generated in the right place

**Review by turbomam — APPROVED** [review]

**Comment by pkalita-lbl** [comment]
> can you remind me what we ahd to do to get yarn installed and working on my computer

Typically if you have Node >= 16 installed, you can enable yarn by running `corepack enable`. I think we ran into some confusion because you didn't have `corepack` on your system even though you had a recent version of Node. We solved it by installing `corepack` with `npm install -g corepack` and then running `corepack enable`.

You can think of yarn as being analogous to poetry in the Python world. You don't have to setup yarn itself for every project; that's a system-wide thing. Within a project `yarn` is like `poetry install`, `yarn <cmd>` is like `poetry run <cmd>`.

> Assumes that JSON version of schema has been generated in the right place

Yes, the `web` directory is set up to read schema JSON files out of the `web/schemas` directory. I checked in the JSON version of `dh_testing` in that directory and there is a Makefile target to update it.

**Pull request merged**
